# Generated by Django 3.1.7 on 2021-03-02 15:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='desired_service',
            field=models.CharField(blank=True, choices=[('Request a quote for switching to Cricket', 'Request a quote for switching to Cricket'), ('Request a call regarding ongoing promotions', 'Request a call regarding ongoing promotions'), ('Upgrading existing devices/plans', 'Upgrading existing devices/plans'), ('Looking to purchase a specific device', 'Looking to purchase a specific device'), ('Need information on adding new lines', 'Need information on adding new lines'), ('Other', 'Other')], default='Request a quote for switching to Cricket', max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message_from_client',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='Other messages/information'),
        ),
    ]
