# Generated by Django 3.1.7 on 2021-03-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210302_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
