# Generated by Django 3.1.7 on 2021-03-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210317_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='medium',
        ),
        migrations.AddField(
            model_name='lead',
            name='auto_pay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_last_interacted',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='rate_plan',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Inquired', 'Inquired'), ('Contacted', 'Contacted'), ('Sold', 'Sold'), ('Unsellable', 'Unsellable')], default='Inquired', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricket_protect', models.BooleanField(blank=True, default=False, null=True)),
                ('current_device_type', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('upgrade_eligibility_date', models.DateField(blank=True, default=None, null=True)),
                ('lead', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
