# Generated by Django 3.1.7 on 2021-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210318_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='rate_plan',
            field=models.CharField(blank=True, choices=[('More', 'More'), ('Core', 'Core'), ('10GB', '10GB'), ('2GB', '2GB')], default=None, max_length=4, null=True),
        ),
    ]
