# Generated by Django 3.1.7 on 2021-03-22 20:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_employee_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None),
        ),
    ]
